name: Docs with Typedoc
on:
    workflow_call:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: pages
    cancel-in-progress: true

jobs:
    setup:
        uses: Kryft-Studios/workflows/.github/workflows/setupPnpm.yml@main
        with:
            install-deps: true
    buildDocs:
        runs-on: ubuntu-latest
        steps:
            - run: pnpm exec typedoc
            
            - uses: actions/configure-pages@v5
            - uses: actions/upload-pages-artifact@v3
              with:
                path: ./docs
    deploy: 
        environment: 
            #lwk vscode github extension SCREAMS
            name: "github-pages"
            url: ${{ steps.deployment.outputs.page_url }} 
        runs-on: ubuntu-latest 
        needs: buildDocs
        steps: 
            - name: Deploy to GitHub Pages 
              id: deployment 
              uses: actions/deploy-pages@v4
            