name: Linting with JS
on:
    workflow_call:
jobs:
  setup:
    uses: Kryft-Studios/workflows/.github/workflows/setupPnpm.yml@main
    with:
      install-deps: true
  lint:
        runs-on: ubuntu-latest
        steps:
            - run: pnpm exec eslint