name: Typecheck Typescript
on:
    workflow_call:
jobs:
    setup:
        uses: Kryft-Studios/workflows/.github/workflows/setupPnpm.yml@main
        with:
            install-deps: true
    typecheck:
        runs-on: ubuntu-latest
        steps:
            - run: pnpm exec tsc